const ADD_LINK_ACTION = 'ADD_LINK_ACTION';
const CLEAR_LINK_ACTION = 'CLEAR_LINK_ACTION';
const REMOVE_LINK_ACTION = 'REMOVE_LINK_ACTION';

export {ADD_LINK_ACTION, CLEAR_LINK_ACTION, REMOVE_LINK_ACTION};