SELECT * FROM employee WHERE SALARY >= 5000 AND SALARY <= 11000;
SELECT * FROM employee WHERE CONTRACT_LENGTH < 2;
INSERT INTO employee (FIRST_NAME, LAST_NAME, SALARY, CONTRACT_LENGTH) VALUES ('Tai Man', 'Chan', 7000, 2), ('John', 'Appleseed', 12000, 1);
UPDATE employee SET SALARY = 8000, CONTRACT_LENGTH = 2 WHERE FIRST_NAME = 'Nancy' AND LAST_NAME = 'Greenburg';
SELECT * FROM employee ORDER BY SALARY DESC;